application: gift-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
          
- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /model
  static_dir: model
  secure: always

- url: /ui
  static_dir: ui
  secure: always

- url: /.*
  static_files: gift-o-matic.html
  upload: gift-o-matic.html
  secure: always
  http_headers:
      Strict-Transport-Security: max-age=10886400; includeSubDomains